// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Amenity struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Description *string `json:"description"`
}

type NewAmenity struct {
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	Latitude    float64         `json:"latitude"`
	Longitude   float64         `json:"longitude"`
	Photo       *graphql.Upload `json:"photo"`
	Description *string         `json:"description"`
}
